// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Button': string;
  'Text': string;
  'adaptedForHeader': string;
  'filled_blueGreenGradient': string;
  'outlined': string;
  'size_md': string;
  'theme_arrow': string;
  'wide': string;
}
export const cssExports: CssExports;
export default cssExports;
