// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Checkbox': string;
  'CustomInput': string;
  'Input': string;
  'SmallText': string;
  'Text': string;
  'TextWrapper': string;
  'Title': string;
  'Wrapper': string;
  'type_toggle': string;
}
export const cssExports: CssExports;
export default cssExports;
